apiVersion: v1
kind: ServiceAccount
metadata:
  name:  distributed-geobroker
  namespace: distributed-geobroker-namespace
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: distributed-geobroker
  namespace: distributed-geobroker-namespace
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: distributed-geobroker
  namespace: distributed-geobroker-namespace
subjects:
- kind: ServiceAccount
  name:  distributed-geobroker
  namespace: distributed-geobroker-namespace
roleRef:
  kind: ClusterRole
  name: distributed-geobroker
  apiGroup: rbac.authorization.k8s.io