apiVersion: v1
kind: ServiceAccount
metadata:
  name:  default
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default
  namespace: default
subjects:
- kind: ServiceAccount
  name:  default
  namespace: default
roleRef:
  kind: ClusterRole
  name: default
  apiGroup: rbac.authorization.k8s.io