#!/bin/bash 

cd /terraformEKS

terraform init

terraform plan

terraform apply -auto-approve

aws eks --region eu-central-1 update-kubeconfig --name distributed-geobroker-cluster

terraform output config-map > config-map-aws-auth.yaml

kubectl apply -f config-map-aws-auth.yaml

cd ../

cd /ansible

ansible-playbook full-set-up.yaml

kubectl get svc