---
- hosts: localhost
  tasks:
    ## Install Kubernetes metrics-server
    - name: Get metrics-server repo
      git:
        repo: "https://github.com/kubernetes-incubator/metrics-server.git"
        dest: metrics-server

    - name: "Remove runAsNonRoot from metrics deployment"
      lineinfile:
        dest: metrics-server/deploy/1.8+/metrics-server-deployment.yaml
        regexp: "runAsNonRoot: true"
        state: absent
      register: example1out

    - name: Update metrics-server/deploy/1.8+/metrics-server-deployment.yaml
      lineinfile:
        dest: metrics-server/deploy/1.8+/metrics-server-deployment.yaml
        line: "{{ item }}"
        state: present
      with_items:
      - "        command:"
      - "          - /metrics-server"
      - "          - --kubelet-insecure-tls"
      - "          - --kubelet-preferred-address-types=InternalIP,Hostname,InternalDNS,ExternalDNS,ExternalIP"
      - "          - --metric-resolution=30s"

    - name: Apply metrics-server manifest
      shell: kubectl apply -f metrics-server/deploy/1.8+/

    - name: Remove metrics-server repo
      file:
        path: ./metrics-server
        state: absent

    # Install Kubernetes Dashboard(UI)
    - name: Apply kubernetes dashboard
      shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml

    - name: Access dashboard via proxy
      shell: kubectl proxy --port=8080 --address='0.0.0.0' --disable-filter=true &

