---
- hosts: localhost
  tasks:
    - pip:
        name: openshift
        
    - name: create namespaces
      k8s:
        state: present
        src: ./namespaces/cluster-namespaces.yaml

    - name: create default roles
      k8s:
        state: present
        src: ./roles/cluster-role-binding-default.yaml

    - name: create roles for namespace
      k8s:
        state: present
        src: ./roles/cluster-role-binding-namespace.yaml

    - name: Launch the cluster deployment
      k8s:
        state: present
        src: ./cluster/cluster-deployment.yaml
    
    - name: create cluster service
      k8s:
        state: present
        src: ./cluster/cluster-service.yaml

#    # Install Kubernetes metrics-server and Dashboard(UI)
#    - name: Get metrics-server repo
#      git:
#        repo: "https://github.com/kubernetes-incubator/metrics-server.git"
#        dest: metrics-server
#
#    - name: Update metrics-server/deploy/1.8+/metrics-server-deployment.yaml
#      lineinfile:
#        dest: metrics-server/deploy/1.8+/metrics-server-deployment.yaml
#        line: "{{ item }}"
#        state: present
#      with_items:
#      - "        command:"
#      - "          - /metrics-server"
#      - "          - --v=2"
#      - "          - --kubelet-insecure-tls"
#      - "          - --kubelet-preferred-address-types=InternalIP"
#
#    - name: Apply metrics-server manifest
#      shell: kubectl apply -f metrics-server/deploy/1.8+/
#
#    - name: Remove metrics-server repo
#      file:
#        path: ./metrics-server
#        state: absent
#
#    - name: Apply kubernetes dashboard
#      shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml
#
#    - name: Access dashboard via proxy
#      shell: kubectl proxy --port=8080 --address='0.0.0.0' --disable-filter=true &