kind: Service
apiVersion: v1
metadata:
  name: master-thesis-cluster
spec:
  type: NodePort
  selector:
    app: master-thesis-cluster
  ports:
  - protocol: TCP
    name: management
    port: 8558
    targetPort: management
  - protocol: TCP
    name: api
    port: 8000
    targetPort: api