apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-thesis
  namespace: master-thesis-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: master-thesis-cluster
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: master-thesis-cluster
    spec:
      serviceAccountName: master-thesis-cluster
      containers:
      - image: master-thesis-cluster:1.0.0
        imagePullPolicy: IfNotPresent
        name: master-thesis-cluster
        resources:
          requests:
            cpu: "0.3"
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: remoting
          containerPort: 2552
        - name: api
          containerPort: 8000
        - name: management
          containerPort: 8558
        readinessProbe:
          httpGet:
            path: "/ready"
            port: management
          initialDelaySeconds: 30
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: "/alive"
            port: management
          initialDelaySeconds: 60
          periodSeconds: 10
